#################
#               #
#    Spring     #
#               #
#################
server.port: 8080
spring: 
   thymeleaf.cache: false
   datasource.url: jdbc:sqlite:${user.dir}/db/data.db
#################
#               #
# elasticsearch #
#               #
################# 
elasticsearch.rest.urls: http://localhost:9200,http://localhost:9200
